/*
Purpose:
Validate standardized rows loaded from extraction results for the current
document/parse/schema/extraction run.

ND Medicaid fee schedule schema specific.

Checks:
1. Source-to-target row reconciliation
2. Dedupe-key validation
3. Required field/null checks
4. Procedure code quality
5. Modifier quality
6. Medicaid fee quality
7. Page coverage
*/

/*
Session prerequisites:
Run 00_config.sql to set DATABASE, SCHEMA, and WAREHOUSE, parameters, and stage name before running this script.
*/

/*
1. SOURCE-TO-TARGET ROW COUNT RECONCILIATION
*/
SELECT
    SOURCE_ROW_COUNT,
    STANDARDIZED_ROW_COUNT,
    STANDARDIZED_ROW_COUNT - SOURCE_ROW_COUNT AS ROW_COUNT_DIFFERENCE,
    CASE
        WHEN STANDARDIZED_ROW_COUNT - SOURCE_ROW_COUNT = 0 THEN 'PASS'
        ELSE 'REVIEW'
    END AS ROW_COUNT_STATUS
FROM (
    SELECT
        (
            SELECT COUNT(*)
            FROM RAW_EXTRACTION_RESULTS AS R,
            LATERAL FLATTEN(
                INPUT => R.RAW_EXTRACTION_RESPONSE:response:fee_schedule:procedure_code
            ) AS CODE
            WHERE R.DOCUMENT_ID = $DOCUMENT_ID
              AND R.PARSE_RUN_ID = $PARSE_RUN_ID
              AND R.EXTRACTION_VERSION = $EXTRACTION_VERSION
              AND R.SCHEMA_VERSION = $SCHEMA_VERSION
              AND R.RUN_STATUS = $RUN_STATUS
        ) AS SOURCE_ROW_COUNT,
        (
            SELECT COUNT(*)
            FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
            WHERE DOCUMENT_ID = $DOCUMENT_ID
              AND PARSE_RUN_ID = $PARSE_RUN_ID
              AND EXTRACTION_VERSION = $EXTRACTION_VERSION
              AND SCHEMA_VERSION = $SCHEMA_VERSION
        ) AS STANDARDIZED_ROW_COUNT
);


/*
2. DUPLICATE CHECK (matches Step 2 dedupe key)
*/
SELECT
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'REVIEW'
    END AS DEDUPE_KEY_STATUS,
    COUNT(*) AS DUPLICATE_KEY_GROUPS
FROM (
    SELECT
        DOCUMENT_ID,
        PARSE_RUN_ID,
        EXTRACTION_VERSION,
        PAGE_NUMBER,
        SOURCE_ROW_INDEX,
        COUNT(*) AS ROWS_IN_GROUP
    FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
    WHERE DOCUMENT_ID = $DOCUMENT_ID
      AND PARSE_RUN_ID = $PARSE_RUN_ID
      AND EXTRACTION_VERSION = $EXTRACTION_VERSION
      AND SCHEMA_VERSION = $SCHEMA_VERSION
    GROUP BY
        DOCUMENT_ID,
        PARSE_RUN_ID,
        EXTRACTION_VERSION,
        PAGE_NUMBER,
        SOURCE_ROW_INDEX
    HAVING COUNT(*) > 1
);


/*
3. REQUIRED FIELD / NULL CHECKS
*/
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(PROCEDURE_CODE IS NULL) AS NULL_PROCEDURE_CODE_COUNT,
    COUNT_IF(MODIFIER IS NULL) AS NULL_MODIFIER_COUNT,
    COUNT_IF(MEDICAID_FEE IS NULL) AS NULL_MEDICAID_FEE_COUNT
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
  AND PARSE_RUN_ID = $PARSE_RUN_ID
  AND EXTRACTION_VERSION = $EXTRACTION_VERSION
  AND SCHEMA_VERSION = $SCHEMA_VERSION;


/*
4. PROCEDURE CODE QUALITY CHECKS
*/
SELECT
    COUNT(*) AS MALFORMED_PROCEDURE_CODE_COUNT
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
  AND PARSE_RUN_ID = $PARSE_RUN_ID
  AND EXTRACTION_VERSION = $EXTRACTION_VERSION
  AND SCHEMA_VERSION = $SCHEMA_VERSION
  AND PROCEDURE_CODE IS NOT NULL
  AND NOT REGEXP_LIKE(PROCEDURE_CODE, '^[A-Za-z0-9]+$');


SELECT
    LENGTH(PROCEDURE_CODE) AS CODE_LENGTH,
    COUNT(*) AS ROW_COUNT
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
  AND PARSE_RUN_ID = $PARSE_RUN_ID
  AND EXTRACTION_VERSION = $EXTRACTION_VERSION
  AND SCHEMA_VERSION = $SCHEMA_VERSION
  AND PROCEDURE_CODE IS NOT NULL
GROUP BY LENGTH(PROCEDURE_CODE)
ORDER BY CODE_LENGTH;


/*
5. MODIFIER QUALITY CHECKS
*/

-- Total rows should match the standardized row count from Step 1.
SELECT
    MODIFIER,
    COUNT(*) AS ROW_COUNT
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
  AND PARSE_RUN_ID = $PARSE_RUN_ID
  AND EXTRACTION_VERSION = $EXTRACTION_VERSION
  AND SCHEMA_VERSION = $SCHEMA_VERSION
GROUP BY MODIFIER
ORDER BY ROW_COUNT DESC;


SELECT
    COUNT(*) AS INVALID_MODIFIER_COUNT
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
  AND PARSE_RUN_ID = $PARSE_RUN_ID
  AND EXTRACTION_VERSION = $EXTRACTION_VERSION
  AND SCHEMA_VERSION = $SCHEMA_VERSION
  AND MODIFIER IN ('', 'None');


/*
6. MEDICAID_FEE QUALITY CHECKS
*/
SELECT
        COUNT(*) AS TOTAL_ROWS,
        COUNT_IF(MEDICAID_FEE IS NULL) AS NULL_FEE_ROWS,
        COUNT_IF(MEDICAID_FEE <= 0) AS NON_POSITIVE_FEE_ROWS,
        MIN(MEDICAID_FEE) AS MIN_MEDICAID_FEE,
        MAX(MEDICAID_FEE) AS MAX_MEDICAID_FEE,
        CASE
                WHEN COUNT_IF(MEDICAID_FEE IS NULL OR MEDICAID_FEE <= 0) = 0 THEN 'PASS'
                ELSE 'REVIEW'
        END AS MEDICAID_FEE_STATUS
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
    AND PARSE_RUN_ID = $PARSE_RUN_ID
    AND EXTRACTION_VERSION = $EXTRACTION_VERSION
    AND SCHEMA_VERSION = $SCHEMA_VERSION;


-- Optional detail: rows with NULL or non-positive fee.
SELECT
        PAGE_NUMBER,
        SOURCE_ROW_INDEX,
        PROCEDURE_CODE,
        MODIFIER,
        MEDICAID_FEE
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
    AND PARSE_RUN_ID = $PARSE_RUN_ID
    AND EXTRACTION_VERSION = $EXTRACTION_VERSION
    AND SCHEMA_VERSION = $SCHEMA_VERSION
    AND (MEDICAID_FEE IS NULL OR MEDICAID_FEE <= 0)
ORDER BY PAGE_NUMBER, SOURCE_ROW_INDEX
LIMIT 50;


/*
7. PAGE COVERAGE CHECK
*/
WITH RAW_PAGES AS (
    SELECT DISTINCT
        DOCUMENT_ID,
        PAGE_NUMBER
    FROM RAW_EXTRACTION_RESULTS
    WHERE DOCUMENT_ID = $DOCUMENT_ID
      AND PARSE_RUN_ID = $PARSE_RUN_ID
      AND EXTRACTION_VERSION = $EXTRACTION_VERSION
      AND SCHEMA_VERSION = $SCHEMA_VERSION
      AND RUN_STATUS = $RUN_STATUS
),
STANDARDIZED_PAGES AS (
    SELECT DISTINCT
        DOCUMENT_ID,
        PAGE_NUMBER
    FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
    WHERE DOCUMENT_ID = $DOCUMENT_ID
      AND PARSE_RUN_ID = $PARSE_RUN_ID
      AND EXTRACTION_VERSION = $EXTRACTION_VERSION
      AND SCHEMA_VERSION = $SCHEMA_VERSION
)
SELECT
    R.DOCUMENT_ID,
    R.PAGE_NUMBER AS RAW_PAGE_NUMBER,
    S.PAGE_NUMBER AS STANDARDIZED_PAGE_NUMBER,
    CASE
        WHEN S.PAGE_NUMBER IS NULL THEN 'MISSING_FROM_STANDARDIZED'
        ELSE 'PRESENT'
    END AS PAGE_STATUS
FROM RAW_PAGES AS R
LEFT JOIN STANDARDIZED_PAGES AS S
    ON R.DOCUMENT_ID = S.DOCUMENT_ID
   AND R.PAGE_NUMBER = S.PAGE_NUMBER
ORDER BY R.PAGE_NUMBER;
