/*
Purpose:
Validate standardized rows loaded from extraction results for the current
document/parse/schema/extraction run.

NM Medicaid fee schedule schema specific.

Checks:
1. Source-to-target row reconciliation
2. Dedupe-key validation
3. Required field/null checks
4. Procedure code quality
5. Modifier quality
6. Rate quality
7. Page coverage
8. Tax quality
9. VFC quality
10. Price start date quality
11. Pricing note quality
*/

/*
Session prerequisites:
Run 00_config.sql to set DATABASE, SCHEMA, and WAREHOUSE, parameters, and stage name before running this script.
*/

/*
1. SOURCE-TO-TARGET ROW COUNT RECONCILIATION
*/
SELECT
    SOURCE_ROW_COUNT,
    STANDARDIZED_ROW_COUNT,
    STANDARDIZED_ROW_COUNT - SOURCE_ROW_COUNT AS ROW_COUNT_DIFFERENCE,
    CASE
        WHEN STANDARDIZED_ROW_COUNT - SOURCE_ROW_COUNT = 0 THEN 'PASS'
        ELSE 'REVIEW'
    END AS ROW_COUNT_STATUS
FROM (
    SELECT
        (
            SELECT COUNT(*)
            FROM RAW_EXTRACTION_RESULTS AS R,
            LATERAL FLATTEN(
                INPUT => R.RAW_EXTRACTION_RESPONSE:response:fee_schedule:cpt_code
            ) AS CODE
            WHERE R.DOCUMENT_ID = $DOCUMENT_ID
              AND R.PARSE_RUN_ID = $PARSE_RUN_ID
              AND R.EXTRACTION_VERSION = $EXTRACTION_VERSION
              AND R.SCHEMA_VERSION = $SCHEMA_VERSION
              AND R.RUN_STATUS = $RUN_STATUS
        ) AS SOURCE_ROW_COUNT,
        (
            SELECT COUNT(*)
                        FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
            WHERE DOCUMENT_ID = $DOCUMENT_ID
              AND PARSE_RUN_ID = $PARSE_RUN_ID
              AND EXTRACTION_VERSION = $EXTRACTION_VERSION
              AND SCHEMA_VERSION = $SCHEMA_VERSION
        ) AS STANDARDIZED_ROW_COUNT
);


/*
2. DUPLICATE CHECK (matches Step 2 dedupe key)
*/
SELECT
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'REVIEW'
    END AS DEDUPE_KEY_STATUS,
    COUNT(*) AS DUPLICATE_KEY_GROUPS
FROM (
    SELECT
        DOCUMENT_ID,
        PARSE_RUN_ID,
        EXTRACTION_VERSION,
        PAGE_NUMBER,
        SOURCE_ROW_INDEX,
        COUNT(*) AS ROWS_IN_GROUP
        FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
    WHERE DOCUMENT_ID = $DOCUMENT_ID
      AND PARSE_RUN_ID = $PARSE_RUN_ID
      AND EXTRACTION_VERSION = $EXTRACTION_VERSION
      AND SCHEMA_VERSION = $SCHEMA_VERSION
    GROUP BY
        DOCUMENT_ID,
        PARSE_RUN_ID,
        EXTRACTION_VERSION,
        PAGE_NUMBER,
        SOURCE_ROW_INDEX
    HAVING COUNT(*) > 1
);


/*
3. REQUIRED FIELD / NULL CHECKS
*/
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(*) AS STANDARDIZED_ROW_COUNT,
    COUNT_IF(CPT_CODE IS NULL) AS NULL_CPT_CODE_COUNT,
    COUNT_IF(TAX IS NULL) AS NULL_TAX_COUNT,
    COUNT_IF(RATE IS NULL) AS NULL_RATE_COUNT,
    COUNT_IF(PRICING_NOTE IS NULL) AS NULL_PRICING_NOTE_COUNT,
    COUNT_IF(VFC IS NULL) AS NULL_VFC_COUNT,
    COUNT_IF(MODIFIER IS NULL) AS NULL_MODIFIER_COUNT,
    COUNT_IF(RATE_2 IS NULL) AS NULL_RATE_2_COUNT,
    COUNT_IF(PRICE_START_DATE IS NULL) AS NULL_PRICE_START_DATE_COUNT
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
  AND PARSE_RUN_ID = $PARSE_RUN_ID
  AND EXTRACTION_VERSION = $EXTRACTION_VERSION
  AND SCHEMA_VERSION = $SCHEMA_VERSION;


/*
4. PROCEDURE CODE QUALITY CHECKS
*/
SELECT
    COUNT(*) AS MALFORMED_CPT_CODE_COUNT
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
  AND PARSE_RUN_ID = $PARSE_RUN_ID
  AND EXTRACTION_VERSION = $EXTRACTION_VERSION
  AND SCHEMA_VERSION = $SCHEMA_VERSION
  AND CPT_CODE IS NOT NULL
  AND NOT REGEXP_LIKE(CPT_CODE, '^[A-Za-z0-9]+$');


SELECT
    LENGTH(CPT_CODE) AS CODE_LENGTH,
    COUNT(*) AS ROW_COUNT
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
  AND PARSE_RUN_ID = $PARSE_RUN_ID
  AND EXTRACTION_VERSION = $EXTRACTION_VERSION
  AND SCHEMA_VERSION = $SCHEMA_VERSION
  AND CPT_CODE IS NOT NULL
GROUP BY LENGTH(CPT_CODE)
ORDER BY CODE_LENGTH;


/*
5. MODIFIER QUALITY CHECKS
*/

-- Total rows should match the standardized row count from Step 1.
SELECT
    MODIFIER,
    COUNT(*) AS ROW_COUNT
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
  AND PARSE_RUN_ID = $PARSE_RUN_ID
  AND EXTRACTION_VERSION = $EXTRACTION_VERSION
  AND SCHEMA_VERSION = $SCHEMA_VERSION
GROUP BY MODIFIER
ORDER BY ROW_COUNT DESC;


SELECT
    COUNT(*) AS INVALID_MODIFIER_COUNT
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
  AND PARSE_RUN_ID = $PARSE_RUN_ID
  AND EXTRACTION_VERSION = $EXTRACTION_VERSION
  AND SCHEMA_VERSION = $SCHEMA_VERSION
  AND (MODIFIER IS NULL OR MODIFIER IN ('', 'None'));


/*
6. RATE QUALITY CHECKS
*/
SELECT
        COUNT(*) AS TOTAL_ROWS,
        COUNT_IF(RATE IS NULL) AS NULL_RATE_ROWS,
        COUNT_IF(RATE <= 0) AS NON_POSITIVE_RATE_ROWS,
        MIN(RATE) AS MIN_RATE,
        MAX(RATE) AS MAX_RATE,
        CASE
                WHEN COUNT_IF(RATE IS NULL OR RATE <= 0) = 0 THEN 'PASS'
                ELSE 'REVIEW'
        END AS RATE_STATUS
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
    AND PARSE_RUN_ID = $PARSE_RUN_ID
    AND EXTRACTION_VERSION = $EXTRACTION_VERSION
    AND SCHEMA_VERSION = $SCHEMA_VERSION;


-- Optional detail: rows with NULL or non-positive rate.
SELECT
        PAGE_NUMBER,
        SOURCE_ROW_INDEX,
        CPT_CODE,
        MODIFIER,
        RATE
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
    AND PARSE_RUN_ID = $PARSE_RUN_ID
    AND EXTRACTION_VERSION = $EXTRACTION_VERSION
    AND SCHEMA_VERSION = $SCHEMA_VERSION
    AND (RATE IS NULL OR RATE <= 0)
ORDER BY PAGE_NUMBER, SOURCE_ROW_INDEX
LIMIT 50;


/*
7. PAGE COVERAGE CHECK
*/
WITH RAW_PAGES AS (
    SELECT DISTINCT
        DOCUMENT_ID,
        PAGE_NUMBER
    FROM RAW_EXTRACTION_RESULTS
    WHERE DOCUMENT_ID = $DOCUMENT_ID
      AND PARSE_RUN_ID = $PARSE_RUN_ID
      AND EXTRACTION_VERSION = $EXTRACTION_VERSION
      AND SCHEMA_VERSION = $SCHEMA_VERSION
      AND RUN_STATUS = $RUN_STATUS
),
STANDARDIZED_PAGES AS (
    SELECT DISTINCT
        DOCUMENT_ID,
        PAGE_NUMBER
        FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
    WHERE DOCUMENT_ID = $DOCUMENT_ID
      AND PARSE_RUN_ID = $PARSE_RUN_ID
      AND EXTRACTION_VERSION = $EXTRACTION_VERSION
      AND SCHEMA_VERSION = $SCHEMA_VERSION
)
SELECT
    R.DOCUMENT_ID,
    R.PAGE_NUMBER AS RAW_PAGE_NUMBER,
    S.PAGE_NUMBER AS STANDARDIZED_PAGE_NUMBER,
    CASE
        WHEN S.PAGE_NUMBER IS NULL THEN 'MISSING_FROM_STANDARDIZED'
        ELSE 'PRESENT'
    END AS PAGE_STATUS
FROM RAW_PAGES AS R
LEFT JOIN STANDARDIZED_PAGES AS S
    ON R.DOCUMENT_ID = S.DOCUMENT_ID
   AND R.PAGE_NUMBER = S.PAGE_NUMBER
ORDER BY R.PAGE_NUMBER;


/*
8. TAX QUALITY CHECKS
*/
SELECT
        COUNT(*) AS TOTAL_ROWS,
        COUNT_IF(TAX IS NULL) AS NULL_TAX_ROWS,
        COUNT_IF(TAX IS NOT NULL AND TRIM(TAX) = '') AS BLANK_TAX_ROWS,
        COUNT_IF(
                TAX IS NOT NULL
                AND UPPER(TRIM(TAX)) IN ('NONE', 'N/A', 'NA', 'NULL')
        ) AS NULL_LIKE_TAX_ROWS,
        COUNT(DISTINCT TAX) AS DISTINCT_TAX_VALUES,
        CASE
                WHEN COUNT(*) = COUNT_IF(TAX IS NULL) THEN 'ALL_NULL'
                ELSE 'REVIEW_DISTRIBUTION'
        END AS TAX_STATUS
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
    AND PARSE_RUN_ID = $PARSE_RUN_ID
    AND EXTRACTION_VERSION = $EXTRACTION_VERSION
    AND SCHEMA_VERSION = $SCHEMA_VERSION;


-- Optional detail: value distribution for tax, including NULL.
SELECT
        COALESCE(TAX, '<<NULL>>') AS TAX_VALUE,
        COUNT(*) AS ROW_COUNT
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
    AND PARSE_RUN_ID = $PARSE_RUN_ID
    AND EXTRACTION_VERSION = $EXTRACTION_VERSION
    AND SCHEMA_VERSION = $SCHEMA_VERSION
GROUP BY COALESCE(TAX, '<<NULL>>')
ORDER BY ROW_COUNT DESC, TAX_VALUE;


/*
9. VFC QUALITY CHECKS
*/
SELECT
        COUNT(*) AS TOTAL_ROWS,
        COUNT_IF(VFC IS NULL) AS NULL_VFC_ROWS,
        COUNT_IF(VFC IS NOT NULL AND TRIM(VFC) = '') AS BLANK_VFC_ROWS,
        COUNT_IF(
                VFC IS NOT NULL
                AND UPPER(TRIM(VFC)) IN ('NONE', 'N/A', 'NA', 'NULL')
        ) AS NULL_LIKE_VFC_ROWS,
    COUNT_IF(
        VFC IS NOT NULL
        AND UPPER(TRIM(VFC)) = 'VFC ANTIGEN'
    ) AS VALID_VFC_ANTIGEN_ROWS,
    COUNT_IF(
        VFC IS NOT NULL
        AND TRIM(VFC) <> ''
        AND UPPER(TRIM(VFC)) NOT IN ('NONE', 'N/A', 'NA', 'NULL', 'VFC ANTIGEN', 'VFC')
    ) AS INVALID_VFC_VALUE_ROWS,
        COUNT(DISTINCT VFC) AS DISTINCT_VFC_VALUES,
        CASE
        WHEN COUNT(*) = COUNT_IF(VFC IS NULL) THEN 'ALL_NULL'
        WHEN COUNT_IF(
            VFC IS NOT NULL
            AND TRIM(VFC) <> ''
            AND UPPER(TRIM(VFC)) NOT IN ('NONE', 'N/A', 'NA', 'NULL', 'VFC ANTIGEN', 'VFC')
        ) > 0 THEN 'REVIEW_INVALID_VALUES'
                ELSE 'REVIEW_DISTRIBUTION'
        END AS VFC_STATUS
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
    AND PARSE_RUN_ID = $PARSE_RUN_ID
    AND EXTRACTION_VERSION = $EXTRACTION_VERSION
    AND SCHEMA_VERSION = $SCHEMA_VERSION;


-- Optional detail: value distribution for VFC, including NULL.
SELECT
        COALESCE(VFC, '<<NULL>>') AS VFC_VALUE,
        COUNT(*) AS ROW_COUNT
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
    AND PARSE_RUN_ID = $PARSE_RUN_ID
    AND EXTRACTION_VERSION = $EXTRACTION_VERSION
    AND SCHEMA_VERSION = $SCHEMA_VERSION
GROUP BY COALESCE(VFC, '<<NULL>>')
ORDER BY ROW_COUNT DESC, VFC_VALUE;


-- Optional detail: unexpected VFC values (excluding NULL-like, VFC Antigen, and VFC).
SELECT
        VFC,
        COUNT(*) AS ROW_COUNT
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
    AND PARSE_RUN_ID = $PARSE_RUN_ID
    AND EXTRACTION_VERSION = $EXTRACTION_VERSION
    AND SCHEMA_VERSION = $SCHEMA_VERSION
    AND VFC IS NOT NULL
    AND TRIM(VFC) <> ''
    AND UPPER(TRIM(VFC)) NOT IN ('NONE', 'N/A', 'NA', 'NULL', 'VFC ANTIGEN', 'VFC')
GROUP BY VFC
ORDER BY ROW_COUNT DESC, VFC;


/*
10. PRICE_START_DATE QUALITY CHECKS
*/
SELECT
        COUNT(*) AS TOTAL_ROWS,
        COUNT_IF(PRICE_START_DATE IS NULL) AS NULL_PRICE_START_DATE_ROWS,
        COUNT_IF(PRICE_START_DATE > CURRENT_DATE()) AS FUTURE_PRICE_START_DATE_ROWS,
        MIN(PRICE_START_DATE) AS MIN_PRICE_START_DATE,
        MAX(PRICE_START_DATE) AS MAX_PRICE_START_DATE,
        CASE
                WHEN COUNT_IF(PRICE_START_DATE > CURRENT_DATE()) > 0 THEN 'REVIEW_FUTURE_DATES'
                ELSE 'PASS'
        END AS PRICE_START_DATE_STATUS
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
    AND PARSE_RUN_ID = $PARSE_RUN_ID
    AND EXTRACTION_VERSION = $EXTRACTION_VERSION
    AND SCHEMA_VERSION = $SCHEMA_VERSION;


-- Optional detail: rows with future price start dates.
SELECT
        PAGE_NUMBER,
        SOURCE_ROW_INDEX,
        CPT_CODE,
        PRICE_START_DATE
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
    AND PARSE_RUN_ID = $PARSE_RUN_ID
    AND EXTRACTION_VERSION = $EXTRACTION_VERSION
    AND SCHEMA_VERSION = $SCHEMA_VERSION
    AND PRICE_START_DATE > CURRENT_DATE()
ORDER BY PAGE_NUMBER, SOURCE_ROW_INDEX
LIMIT 50;


/*
11. PRICING_NOTE QUALITY CHECKS
*/
SELECT
        COUNT(*) AS TOTAL_ROWS,
        COUNT_IF(PRICING_NOTE IS NULL) AS NULL_PRICING_NOTE_ROWS,
        COUNT_IF(PRICING_NOTE IS NOT NULL AND TRIM(PRICING_NOTE) = '') AS BLANK_PRICING_NOTE_ROWS,
        COUNT_IF(
                PRICING_NOTE IS NOT NULL
                AND UPPER(TRIM(PRICING_NOTE)) IN ('NONE', 'N/A', 'NA', 'NULL')
        ) AS NULL_LIKE_PRICING_NOTE_ROWS,
        COUNT(DISTINCT PRICING_NOTE) AS DISTINCT_PRICING_NOTE_VALUES,
        CASE
                WHEN COUNT(*) = COUNT_IF(PRICING_NOTE IS NULL) THEN 'ALL_NULL'
                ELSE 'REVIEW_DISTRIBUTION'
        END AS PRICING_NOTE_STATUS
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
    AND PARSE_RUN_ID = $PARSE_RUN_ID
    AND EXTRACTION_VERSION = $EXTRACTION_VERSION
    AND SCHEMA_VERSION = $SCHEMA_VERSION;


-- Optional detail: value distribution for pricing note, including NULL.
SELECT
        COALESCE(PRICING_NOTE, '<<NULL>>') AS PRICING_NOTE_VALUE,
        COUNT(*) AS ROW_COUNT
FROM IDENTIFIER($STANDARDIZED_TABLE_NAME)
WHERE DOCUMENT_ID = $DOCUMENT_ID
    AND PARSE_RUN_ID = $PARSE_RUN_ID
    AND EXTRACTION_VERSION = $EXTRACTION_VERSION
    AND SCHEMA_VERSION = $SCHEMA_VERSION
GROUP BY COALESCE(PRICING_NOTE, '<<NULL>>')
ORDER BY ROW_COUNT DESC, PRICING_NOTE_VALUE;
